disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - function_parameter_count
  - statement_position
  - trailing_whitespace
  - line_length
  - todo
  - type_name
  - vertical_whitespace

included:
  - Sources
  - Tests

identifier_name:
  max_length:
    warning: 100
    error: 150   
  excluded:
    - id
    - x
    - y
    - dx
    - dy
    - vc
